name: hr_management
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  animated_widgets: ^1.1.0
  bloc: ^7.0.0
  cached_network_image: ^3.1.0
  charts_flutter: ^0.11.0
  connectivity: ^3.0.3
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  equatable: ^2.0.3
  file_picker: ^3.0.3
  flip_card: ^0.5.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.1.0
  flutter_breadcrumb: ^1.0.1
  flutter_downloader: ^1.6.1
  flutter_form_bloc: ^0.20.4
  flutter_inappwebview: ^5.3.2
  flutter_simple_treeview: ^2.0.2
  flutter_slidable: ^0.6.0
  flutter_sound: ^8.3.4
  flutter_speed_dial: ^4.1.0
  flutter_staggered_grid_view: ^0.4.0
  flutter_svg: ^0.22.0
  # geocoder: ^0.2.1
  geolocator: ^7.1.0
  hydrated_bloc: ^7.0.1
  image_picker: ^0.8.2
  intl: ^0.17.0
  location: ^4.1.1
  mime_type: ^1.0.0
  open_file: ^3.2.1
  path_provider: ^2.0.1
  permission_handler: ^8.1.6
  rxdart: ^0.27.1
  shared_preferences: ^2.0.6
  sizer: ^2.0.13
  sqflite: ^2.0.0+3
  syncfusion_flutter_charts: ^19.2.47+1
  syncfusion_flutter_gauges: ^19.2.51
  video_player: ^2.1.12
  webview_flutter: ^2.0.10
  geocoding: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  listizer:
    path: ./listizer

flutter:
  uses-material-design: true
  assets:
    - assets/formio.html
    - assets/formio.full.css
    - assets/formio.full.js
    - assets/images/
    - assets/icons/

  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
