name: hr_management
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_widgets: ^1.1.0
  bloc: ^8.0.3
  cached_network_image: ^3.2.1
  # charts_flutter: ^0.11.0
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.5
  device_info_plus: ^3.2.0
  dio: ^4.0.6
  # dropdown_button2: ^1.2.2
  equatable: ^2.0.3
  file_picker: ^4.6.1
  flip_card: ^0.7.0
  # flutter_bloc: ^7.3.0
  flutter_breadcrumb: ^1.0.1
  flutter_downloader: ^1.10.2
  # flutter_form_bloc: ^0.20.4
  # flutter_inappwebview: ^5.4.3+7
  flutter_material_color_picker: ^1.1.0+2
  # flutter_simple_treeview: ^3.0.1
  flutter_slidable: ^3.0.1
  # flutter_sound: ^8.3.4
  flutter_speed_dial: ^6.0.0
  flutter_staggered_grid_view: ^0.7.0
  # flutter_svg: ^0.22.0
  geocoding: ^2.0.4
  geolocator: ^10.1.0
  hydrated_bloc: ^9.1.3
  image_picker: ^0.8.5+3
  intl: ^0.18.0
  location: ^5.0.3
  mime_type: ^1.0.0
  # open_file: ^3.2.1
  path_provider: ^2.0.11
  percent_indicator: ^4.2.2
  permission_handler: ^10.0.0
  rxdart: ^0.27.4
  shared_preferences: ^2.0.15
  sizer: ^2.0.15
  sqflite: ^2.0.3
  syncfusion_flutter_charts: ^23.2.7
  syncfusion_flutter_gauges: ^23.2.7
  video_player: ^2.4.5
  webview_flutter: ^3.0.4
  image_painter: ^0.6.1
  flutter_archive: ^5.0.0
  file: ^6.1.4
  # workmanager: ^0.5.1
  # flutter_local_notifications: ">=12.0.4 <13.0.0"
  latlong2: ^0.9.0
  flutter_background_geolocation: ^4.11.1
  http: ^1.1.2
  # google_maps_flutter: ^0.5.11
  # google_map_polyline: ^0.2.0
  # google_map_webservices:
  # flutter_google_places: ^0.2.0

  

dev_dependencies:
  flutter_lints: ^3.0.1
  synergy_nts:
    path: ./synergy_nts
  synergy_drawer:
    path: ./synergy_drawer

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
