name: hr_management
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_widgets: ^1.1.0
  bloc: ^7.0.0
  connectivity: ^3.0.3
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  equatable: ^2.0.0
  flip_card: ^0.5.0
  flutter_bloc: ^7.0.0
  flutter_form_bloc: ^0.20.4
  flutter_inappwebview: ^5.3.2
  flutter_slidable: ^0.6.0
  flutter_svg: ^0.22.0
  geocoder: ^0.2.1
  geolocator: ^7.1.0
  hydrated_bloc: ^7.0.0
  location: ^4.3.0
  path_provider: ^2.0.1
  rxdart: ^0.27.1
  sizer: ^2.0.13
  sqflite: ^2.0.0+3
  webview_flutter: ^2.0.10
  charts_flutter: ^0.11.0
  flutter_staggered_grid_view: ^0.4.0
  syncfusion_flutter_charts: ^19.2.47+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  listizer:
    path: ./listizer

flutter:
  uses-material-design: true
  assets:
    # - assets/icons/
    - assets/formio.min.js
    - assets/images/

  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300
