name: hr_management
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  bloc: ^7.0.0
  connectivity: ^3.0.3
  cupertino_icons: ^1.0.2
  equatable: ^2.0.0
  flutter_bloc: ^7.0.0
  flutter_svg: ^0.22.0
  hydrated_bloc: ^7.0.0
  geolocator: ^7.1.0
  location: ^4.3.0
  path_provider: ^2.0.1
  sqflite: ^2.0.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    # - assets/icons/
    - assets/images/

  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300
