name: synergy_nts
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^2.3.5
  dio: ^4.0.6
  equatable: ^2.0.3
  file_picker: ^4.6.1
  flutter_bloc: ^8.1.1
  flutter_downloader: ^1.8.0+1
  flutter_form_bloc: ^0.30.1
  # flutter_map: ">=0.11.0 <=1.1.1"
  flutter_speed_dial: ^6.0.0
  # geocoding: ^2.0.1
  # google_maps_flutter: ^2.1.8
  image_picker: ^0.8.5+3
  # latlong: ^0.6.1
  # location: ^4.4.0
  mime_type: ^1.0.0
  open_file: ^3.2.1
  path_provider: ^2.0.11
  permission_handler: ^10.0.0
  rxdart: ^0.27.4
  sizer: ^2.0.15
  video_player: ^2.4.5
  # geolocator: ^9.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  assets:
    - lib/assets/images/
